# Generated by Django 5.2.6 on 2025-11-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('blood_pressure', models.IntegerField(help_text='bp (mm/Hg)')),
                ('specific_gravity', models.DecimalField(decimal_places=3, help_text='sg (Hydration status, e.g., 1.020)', max_digits=4)),
                ('albumin', models.IntegerField(help_text='al (Proteinuria level 0-5)')),
                ('sugar', models.IntegerField(help_text='su (Sugar level 0-5)')),
                ('serum_creatinine', models.DecimalField(decimal_places=2, help_text='sc (Kidney decline indicator)', max_digits=5)),
                ('prediction_result', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
