# Generated by Django 5.2.6 on 2025-11-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='egfr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated Glomerular Filtration Rate', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='proteinuria',
            field=models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive')], default='Negative', max_length=20),
        ),
    ]
