# Generated by Django 5.2.6 on 2025-11-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_patientrecord_egfr_patientrecord_proteinuria'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='risk_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='albumin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='egfr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='prediction_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='proteinuria',
            field=models.CharField(default='Negative', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='serum_creatinine',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='specific_gravity',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='sugar',
            field=models.IntegerField(),
        ),
    ]
