# Generated by Django 6.0.2 on 2026-04-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0004_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='assigned_department',
            field=models.CharField(default='Pending Triage', max_length=100),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='doctor_feedback',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='routing_status',
            field=models.CharField(default='Unassigned', max_length=50),
        ),
    ]
