# Generated by Django 6.0.2 on 2026-04-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0006_customcureplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='proteinuria',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='hemoglobin',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='albumin',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='blood_pressure',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='egfr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='prediction_result',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='risk_level',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='serum_creatinine',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='specific_gravity',
            field=models.FloatField(default=1.01),
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='sugar',
            field=models.FloatField(default=0.0),
        ),
    ]
